language: php

php:
    - 5.3
    - 5.4

before_script: composer install --dev

script:
    - bin/atoum -d tests/units

notifications:
    email:
        recipients:
            - py.stephane1@gmail.com
        on_success: change
        on_failure: change
